# This was written by an AI. HA!
# I hate writing yaml. I'm glad a computer can do it for me.

name: Test Mojolicious Application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: perl:latest
        ports:
          - 8080:8080

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libmojolicious-perl liblist-moreutils-perl libmojolicious-plugin-renderfile-perl libpath-tiny-perl libmime-types-perl

    - name: Start Sakisafe
      run: |
        hypnotoad http/sakisafe.pl

    - name: Test Sakisafe
      run: |
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080

        # LOLOLOLOLOLOLOLO
        curl -X POST -F "file=@/etc/passwd" http://localhost:8080
